name: flutter_image_cropper
description: The flutter package to crop the image
version: 0.0.1
homepage: https://github.com/DakshDB/flutter_image_cropper
environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

